<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/maven-v4_0_0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<artifactId>spring-plugin-autoconfigure</artifactId>

	<name>Spring Plugin - Autoconfigure</name>
	<description>Spring Boot auto-configuration for Spring Plugin</description>

	<parent>
		<groupId>org.springframework.plugin</groupId>
		<artifactId>spring-plugin</artifactId>
		<version>4.2.0-SNAPSHOT</version>
	</parent>

	<properties>
		<java-module-name>spring.plugin.autoconfigure</java-module-name>
	</properties>

	<build>
		<resources>
			<resource>
				<directory>src/main/resources</directory>
				<filtering>true</filtering>
			</resource>
			<resource>
				<directory>../src/main/resources</directory>
				<filtering>true</filtering>
				<targetPath>META-INF</targetPath>
			</resource>
		</resources>
	</build>

	<dependencies>

		<dependency>
			<groupId>org.springframework.plugin</groupId>
			<artifactId>spring-plugin-core</artifactId>
			<version>${project.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-autoconfigure</artifactId>
			<version>${spring-boot.version}</version>
		</dependency>

		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-test</artifactId>
			<version>${spring-boot.version}</version>
			<scope>test</scope>
		</dependency>

	</dependencies>

</project>
